# use bitbucket pipeline for
# 1. indentation check
# 2. C++ unit-tests
# 3. jupyter notebook checks

image: image: python:3.5.1

pipelines:
    default:
        - step:  # indentation check
            script:
                - sudo apt-get update
                - sudo apt-get install -y --fix-missing build-essential cmake
                - sudo apt-get install -y --fix-missing python3-setuptools python3-pip
                - pip3 install numpy scipy matplotlib healpy jupyter pytest nbval
                - cd ${BITBUCKET_CLONE_DIR}
                - midkr gsl
                - wget ftp://ftp.gnu.org/gnu/gsl/gsl-latest.tar.gz && tar xzf gsl-latest.tar.gz -C gsl --strip-components 1
                - cd gsl && ./configure --prefix=/tmp/local && make && make install
                - cd ${BITBUCKET_CLONE_DIR}
                - git clone https://github.com/google/googletest.git googletest
                - cd googletest && mkdir build
                - cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/tmp/local .. && make && make install
                - mkdir /tmp/local/src && cp ../googletest/src/* /tmp/local/src
                - cd ${BITBUCKET_CLONE_DIR}
                - mkdir fftw
                - wget http://www.fftw.org/fftw-3.3.8.tar.gz && tar xzf fftw-3.3.8.tar.gz -C fftw --strip-components 1
                - cd fftw && ./configure --enable-threads --enable-openmp --enable-shared --prefix=/tmp/local && make && make install
                - cd ${BITBUCKET_CLONE_DIR} && ./contrib/utilities/download_clang_format && ./contrib/utilities/check_indentation.sh
                - mkdir build
                - cd build && cmake .. && make install && make test
                - export PATH=/tmp/local/hammurabi/bin:${PATH}
                - export LD_LIBRARY_PATH=/tmp/local/hammurabi/lib:${LD_LIBRARY_PATH}
                - cd ${BITBUCKET_CLONE_DIR} && pip3 install .
                - cd ${BITBUCKET_CLONE_DIR}/tutorials && pytest --nbval-lax
