# use bitbucket pipeline for indentation check
#
image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        trigger: manual
        script:
          - ./contrib/utilities/compile_clang_format
          - ./contrib/utilities/check_indentation.sh
