# use bitbucket pipeline for indentation check
#
image: atlassian/default-image:latest
pipelines:
  default:
    - step:
        script:
          - ./contrib/utilities/download_clang_format
          - ./contrib/utilities/check_indentation.sh
